services:
  latidoapp:
    build: .
    container_name: latidoapp
    expose:
      - "5000"
    environment:
      - PYTHONUNBUFFERED=1
      - VIRTUAL_HOST=control3v.com,www.control3v.com
      - VIRTUAL_PORT=5000
    volumes:
      - /home/webservice/uploads:/app/uploads
      - /home/webservice/logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true
