services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - app-network

  latidoapp:
    build: .
    container_name: latidoapp
    restart: unless-stopped
    labels:
      - com.github.jrcs.nginx-proxy.tls.acme=false
    depends_on:
      - nginx-proxy
    expose:
      - "5000"
    environment:
      - PYTHONUNBUFFERED=1
      - VIRTUAL_HOST=control3v.com,www.control3v.com
      - VIRTUAL_PORT=5000
    volumes:
      - /home/webservice/uploads:/app/uploads
      - /home/webservice/logs:/app/logs
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    restart: always
    labels:
      - com.github.jrcs.nginx-proxy.tls.acme=false
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - VIRTUAL_HOST=phpmyadmin.control3v.com
      - VIRTUAL_PORT=80
    expose:
      - "80"
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - /home/mysql/data:/var/lib/mysql
    ports:
      - "5433:3306"
    networks:
      - app-network

volumes:
  nginx_certs:
    external: true
  nginx_vhost:
    external: true
  nginx_html:
    external: true

networks:
  app-network:
    external: true