services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - /home/mysql/data:/var/lib/mysql
    ports:
      - "5433:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - VIRTUAL_HOST=phpmyadmin.control3v.com
      - VIRTUAL_PORT=80
    expose:
      - "80"
    networks:
      - app-network

networks:
  app-network:
    external: true
